version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-voyant-tools-app-20240604.221544
    tty: true
    ports:
      - "8888:8888"
    environment:
      - CONTAINER_NAME=docker-web-voyant-tools-app