version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-voyant-tools-app-20240604.232910
    tty: true
    ports:
      - "8888:8888"
    environment:
      - CONTAINER_NAME=docker-web-voyant-tools-app
      - LOCAL_VOLUMN_PATH=/data
      - STARTUP_COMMAND="java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -jar VoyantServer.jar headless=true"
      - SERVER_DEFAULT_URI=/